### ISSUE TITLE
Saving Config

### ISSUE THREAD

**Issue by hhdivil** [mailjet/magento-mailjet-plugin-official#23]
When I change anything on any other config pages (e.g. payment methods) - it clears the Mailjet API details out.  We are using Magento 1.9.0.1 & PHP 5.6.

![screenshot from 2019-01-07 15-20-11](https://user-images.githubusercontent.com/25127991/50776011-bd79a500-128f-11e9-9bbd-28563a9d71d4.png)

**Comment by mskochev** [comment]
Hello, thanks for the feedback. The issue reproduces on our environment as well. We'll fix it.

**Comment by mskochev** [comment]
The fix has been released in version 2.0.5 of the plugin. Have a nice day!
